name: Dredd

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest    
    container: pbui/cse-34872-su20-assignments
    steps:
    - uses: actions/checkout@v2
    - name: test
      run:  make test
